apiVersion: v1
kind: Service
metadata:
  name: vault-nlb
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "8200"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /v1/sys/health
    service.beta.kubernetes.io/aws-load-balancer-subnets: ''
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-success-codes: "200"
spec:
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: vault
