# global:
#   enabled: true
#   tlsDisable: true

server:
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-ha-tls/vault-ca.crt
    VAULT_TLSCERT: /vault/userconfig/vault-ha-tls/vault.crt
    VAULT_TLSKEY: /vault/userconfig/vault-ha-tls/vault.key
  volumes:
    - name: userconfig-vault-ha-tls
      secret:
        defaultMode: 420
        secretName: vault-ha-tls
  volumeMounts:
    - mountPath: /vault/userconfig/vault-ha-tls
      name: userconfig-vault-ha-tls
      readOnly: true
  affinity: ""
  ha:
    enabled: true
    raft:
      enabled: true
      config: |
        ui = false
        disable_mlock = true

        listener "tcp" {
          tls_disable = 0
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-ha-tls/vault.crt"
          tls_key_file  = "/vault/userconfig/vault-ha-tls/vault.key"
          tls_client_ca_file = "/vault/userconfig/vault-ha-tls/vault-ca.crt"
        }

        storage "raft" {
          path = "/vault/data"

          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_client_cert_file = "/vault/userconfig/vault-ha-tls/vault.crt"
            leader_client_key_file  = "/vault/userconfig/vault-ha-tls/vault.key"
            leader_ca_cert_file = "/vault/userconfig/vault-ha-tls/vault-ca.crt"
          }

          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_client_cert_file = "/vault/userconfig/vault-ha-tls/vault.crt"
            leader_client_key_file  = "/vault/userconfig/vault-ha-tls/vault.key"
            leader_ca_cert_file = "/vault/userconfig/vault-ha-tls/vault-ca.crt"
          }

          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_client_cert_file = "/vault/userconfig/vault-ha-tls/vault.crt"
            leader_client_key_file  = "/vault/userconfig/vault-ha-tls/vault.key"
            leader_ca_cert_file = "/vault/userconfig/vault-ha-tls/vault-ca.crt"
          }
        }

        service_registration "kubernetes" {}
