apiVersion: v1
kind: Service
metadata:
  name: vault-active-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server
    vault-active: "true"
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8200
      targetPort: 8200
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30000
